openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://localhost:3000
  - url: https://example.com/api/v1
paths:
  /contacts/{contactId}:
    get:
      $ref: '../src/swagger/paths/contacts/{contactId}/get.yaml'
    patch:
      $ref: '../src/swagger/paths/contacts/{contactId}/patch.yaml'
    delete:
      $ref: '../src/swagger/paths/contacts/{contactId}/delete.yaml'
  /contacts:
    get:
      $ref: '../src/swagger/paths/contacts/get.yaml'
    post:
      $ref: '../src/swagger/paths/contacts/post.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    contact:
      type: object
      required:
        - name
        - phoneNumber
        - email
        - isFavourite
        - contactType
        - userId
      properties:
        name:
          description: "Contact's name"
          type: string
          example: 'Alex Boo'
        phoneNumber:
          description: "Contact's phone number"
          type: string
          example: '+380960000000'
        email:
          description: "Contact's email"
          type: string
          format: email
          example: alex@gmail.com
        isFavourite:
          description: "Is this contact a favorite?"
          type: boolean
          example: true
        contactType:
          description: 'Type of contact'
          type: string
          enum: ['personal', 'work']
          example: work
        userId:
          description: "User's id"
          type: string
          example: 65e4decdd286b30065d54af9
        photo:
          description: "Link to contact's photo"
          type: string
          format: uri
          example: 'https://res.cloudinary.com/uqwgdu/image/upload/image.png'
  responses:
    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: integer
                example: 401
              message:
                type: string
                example: Unauthorized
